const Results = [
    { id: 1, title: 'Pizza',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' },
    { id: 2, title: 'Pizza1',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic2.jpg' },
    { id: 3, title: 'Pizza2',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
    { id: 4, title: 'Pizza3',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic5.jpg' },
    { id: 5, title: 'Pizza5',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic6.jpg' },
    { id: 6, title: 'Pizza6',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic7.jpg' },
    { id: 7, title: 'Pizza7',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic8.jpg' },
    { id: 8, title: 'Pizza8',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic9.jpg' },
    { id: 9, title: 'Pizza9',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' },
    { id: 10, title: 'Pizza10',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
    { id: 11, title: 'Pizza11',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' }, 
    { id: 12, title: 'Pizza12',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic2.jpg' },
    { id: 13, title: 'Pizza13',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
    { id: 14, title: 'Pizza14',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic5.jpg' },
    { id: 15, title: 'Pizza15',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic6.jpg' },
    { id: 16, title: 'Pizza16',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic7.jpg' },
    { id: 17, title: 'Pizza17',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic8.jpg' },
    { id: 18, title: 'Pizza18',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic9.jpg' },
    { id: 19, title: 'Pizza19',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' },
    { id: 20, title: 'Pizza20',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
    { id: 21, title: 'Pizza21',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' },
    { id: 22, title: 'Pizza22',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic2.jpg' },
    { id: 23, title: 'Pizza23',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
    { id: 24, title: 'Pizza24',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic5.jpg' },
    { id: 25, title: 'Pizza25',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic6.jpg' },
    { id: 26, title: 'Pizza26',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic7.jpg' },
    { id: 27, title: 'Pizza27', hoverImage:"/pic2.jpg",description: 'Some description text for card', image: '/pic8.jpg' },
    { id: 28, title: 'Pizza28',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic9.jpg' },
    { id: 29, title: 'Pizza29',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic1.jpg' },
    { id: 30, title: 'Pizza30',hoverImage:"/pic2.jpg", description: 'Some description text for card', image: '/pic3.jpg' },
  ];
  
  export default Results;
  